### ISSUE TITLE
Repaso del documento

### ISSUE THREAD

**Issue by ChristophorosD** [hvarg/INF322#2]
Hola Hernan,

Cumplimos este documento, y le queremos repasarlo para añadir más cambios.

Hay partes del análisis, por ejemplo, que yo quería ver si sería más apto poner en la propuesta. Éstos marque con un P en el documento.

Gracias!

**Comment by hvarg** [comment]
Oh, muchas gracias Christopher, 
no he tenido tiempo de subir mis cambios, pero este fin de semana lo haré.
La próxima semana presentaré el proyecto, luego tendremos una revisión con los demás compañeros de intercambio.

Saludos!
