### ISSUE TITLE
Identificación de falencias y oportunidades de mejora - Noticias

### ISSUE THREAD

**Issue by civky** [hvarg/INF322#3]
En la sección de [Noticias](https://github.com/hvarg/INF322#noticias) no comprendo que es lo que se quiere cambiar. ¿Se quiere que siga muestre los links de información del sistema, medios de contactos y sobre la universidad en todas las vistas de la página?.

Además, agregar información sobre la USM ¿también sería una mejora?

saludos :)

**Comment by linneawenall** [comment]
Sí, queremos mudarla a la nueva pagína de noticias para que el usuario siempre pueda buscarla dentro del sistema. Como que ahora no se puede buscar la información de la pagína inicial de nuevo sin salir del sistema, esto sería una mejora.  

Sí, agregar información sobre la USM puede ser una mejora, pero qué tipo de información quieres allá?
/Linnea y Tia

**Comment by hvarg** [comment]
@linneawenall @tiaceline la idea es que lo aclaren en el documento
Con la modificación hecha agregan el link de esta issue cómo comentario del cambio.

**Comment by linneawenall** [comment]
Añadido.
