### ISSUE TITLE
Continuación del curso para estudiantes de intercambio

### ISSUE THREAD

**Issue by linneawenall** [hvarg/INF322#4]
Hola Hernán, 

Te escribo aquí para saber como quieres seguir el curso con nosotros, estudiantes de intercambio. La universidad nos ha prometido los créditos por lo más tarde el 13 de diciembre. Es la responsabilidad de cada profesor de cada curso definir como seguirá con el curso. 

Algunos cursos han decidio que van a usar la nota de las evaluaciones ya finalizados como nota final y que los cursos terminan. Otros dan tareas o siguen con el curso en forma tutoría para seguir avanzando. Como quieres hacer con el curso? 

Como el jueves hemos decidido tener certamen 1 para nosotros. Tienes algunos certamenes de los años anteriores para que sepamos más o menos como son? Y a que hora y dónde realizamos el certamen?

Saludos,
Linnea

**Comment by hvarg** [comment]
Bueno, como les comenté anteriormente los alumnos de intercambio tendrán al menos 2 notas, una por la definición del proyecto y la otra por el certamen uno.
Tengo que hacer dicho certamen tanto a ustedes que vinieron de intercambio, como a los alumnos que se irán de intercambio al año 2020.
Quería que el certamen fuera este jueves, pero le avisé muy tarde a los alumnos que saldrán de intercambio así que ahora estoy viendo fecha con ellos, debería ser el lunes o en algún bloque libre.
Cuando tenga confirmación de la fecha les enviaré un mail con los detalles y certamenes anteriores para que puedan practicar. 

Por cierto, para la nota del proyecto se incluyen las correcciones que los ayudantes pidan, así que atentos si se abren issues en los días que quedan.

Saludos.

**Comment by linneawenall** [comment]
Hola Hernán,

Gracias por responder. Ahora ya hemos planeado para hacer el certamen jueves este semana y yo por lo menos ya tengo dos otros certamenes el lunes, asi que para nosotros sería mucho mejor hacer el certamen este jueves como hemos decidido hace unos dias. Sería posible para nosotros tres de intercambio hacer el certamen este jueves por favor? 

Con esto "Por cierto, para la nota del proyecto se incluyen las correcciones que los ayudantes pidan, así que atentos si se abren issues en los días que quedan." refieres antes de que nos vayamos el 13 de diciembre? La U nos ha promitido que terminarémos por lo más tarde el 13 de diciembre..

**Comment by tiaceline** [comment]
Hola,

Hemos hablado un poco mas, y también creemos cambiar el día de certamen por
el proxima semana, en lunes o jueves. Entonces, podemos hablar mañana sobre
el plan para el semestre y que necesitamos hacer para terminar de 13
diciembre.

Saludos,
Tia

tir. 12. nov. 2019 kl. 16:25 skrev linneawenall <notifications@github.com>:

**Comment by tiaceline** [comment]
Certamen el próximo semana, podemos hablar mañana sobre que dia

tir. 12. nov. 2019, 14:55 skrev hvarg <notifications@github.com>:

**Comment by linneawenall** [comment]
Hola Hernan,

Ahora hemos añadido los cambios de los issues al documento. Estamos listos para tener la nota en SIGA?

Saludos, Linnea
