### ISSUE TITLE
Como editar el estilo de un componente importado

### ISSUE THREAD

**Issue by begandroide** [hvarg/INF322#8]
Supongamos tenemos esta estructura:
```html
<div class="login-layout">
  <wl-card>
     #shadow-root
     <wl-select>
        #shadow-root
        <div id="container">
        </div>
     </wl-select>
  </wl-card>
</div>
```
Quiero añadir un estilo a el id="container", normalmente uno usaría:
```css
wl-select #container{
  height:100%;
}
```
Pero eso no funciona en la estructura del DOM.

Espero una ayuda, gracias.

**Comment by hvarg** [comment]
Bueno depende de que quieras cambiar, por ejemplo `wl-select` [define varias propiedades CSS](https://github.com/andreasbm/weightless/tree/master/src/lib/select#-css-custom-properties).

Por lo general no puedes cambiar el contenido de un `shadow-root` desde afuera de él, en tu ejemplo una solución podría ser:

```html
<div class="login-layout">
  <wl-card>
     #shadow-root
     <wl-select>
        #shadow-root
        <style>
          #container{ height:100%; }
        </style>
        <div id="container">
        </div>
     </wl-select>
  </wl-card>
</div>
```

Puedes ver un ejemplo de como hacer esto programaticamente esto [aquí](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM) en la sección "Styling the shadow DOM".

**Comment by begandroide** [comment]
Gracias profe, me sirvieron las propiedades css de wl-select.
